services: # アプリケーションを動かすための各要素
  python3: # 任意の名称
    restart: always # 実行時に再起動するかどうか
    build: . # ComposeFileを実行し、ビルドされるときのpath
    container_name: 'python3' # コンテナ名
    working_dir: '/root/'
    tty: true # docker-compose up したコンテナを起動させ続ける
    volumes:
      - ./opt:/root/opt
